### ISSUE TITLE
Update template to use carpentries logo

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/training-template#14]
instead of dc or swc logo

**Comment by weaverbel** [comment]
I thought we were still branding workshops by the individual Carpentry @fmichonneau ?

**Comment by fmichonneau** [comment]
This is the repo for instructor training, so I thought it would be good to use the main carpentry logo for this instead of the specific one.

**Comment by weaverbel** [comment]
Aah - that makes sense ! Obviously I got up too early today @fmichonneau - CarpentryCon taskforce meets at 6am!

**Comment by fmichonneau** [comment]
no worries!
