### ISSUE TITLE
location/ accessibility options for online workshops

### ISSUE THREAD

**Issue by raynamharris** [carpentries/training-template#18]
Given that many of these workshops are online, I think that an online workshop could benefit from a few changes to the workshop website, including, but not limited to:

- A header that says "Instructor Training" in bold rather than "online"
- Easy removal of the text about using google maps to find the location
- Removal of the accessibility descriptions, unless they are co-localizing  

If other people agree that this would be a useful feature, I wonder if someone who knows how to write if statements can help make this a little more automated...

**Comment by maneesha** [comment]
I'm closing this as I believe it has been fixed. Anyone can feel free to re-open if it still needs attention.
