### ISSUE TITLE
Add survey links to template

### ISSUE THREAD

**Issue by maneesha** [carpentries/training-template#24]
Now that we have pre/post surveys for instructor trainees can we add them to this template (just like we have for the standard workshop template)?

Can we also have them append the workshop slug (again, like they do for the workshop template)?

Happy to do whatever is needed to make this happen but I'm not sure if there's more to it than adding a link in the template.

**Comment by maneesha** [comment]
I have this same issue in two places
https://github.com/carpentries/instructor-training/issues/698

**Comment by fmichonneau** [comment]
closed in favor of carpentries/styles#332
