### ISSUE TITLE
Conflicting schedules

### ISSUE THREAD

**Issue by arokem** [carpentries/training-template#3]
The schedule in this template is not up-to-date with the schedule in the instructor training materials. 

Compare: https://github.com/swcarpentry/training-template/blob/gh-pages/index.html#L226-L228
with the schedule here: https://swcarpentry.github.io/instructor-training/

I assume the latter should take precedence?

**Comment by gvwilson** [comment]
Yes - good catch.  Can you please PR a fix?

**Comment by ErinBecker** [comment]
Closed with #4
