### ISSUE TITLE
Fix incorrect URL examples

### ISSUE THREAD

**Issue by amyehodge** [carpentries/training-template#34]
Related to incorrect URL in issue #21, the content under customizing your website has a mix of incorrrect URLs and no correct ones, which should be /YYYY-MM-DD-ttt-site. Super confusing.

Currently reads (with incorrect URLs bolded):
1. Go into your newly-created repository, which will be at **https://github.com/your_username/YYYY-MM-DD-site-ttt**. For example, if your username is gvwilson, the repository's URL will be **https://github.com/gvwilson/2016-12-01-miskatonic-ttt.**
.
.
3. Alternatively, if you are already familiar with Git, you can clone the repository to your desktop, edit index.html there, and push your changes back to the repository.

git clone -b gh-pages **https://github.com/your_username/YYYY-MM-DD-site-ttt**

4. When you are done editing, go to the GitHub Pages URL for your workshop and preview your changes. In the example above, this is **https://gvwilson.github.io/2016-12-01-miskatonic.**

**Comment by ErinBecker** [comment]
Thanks for letting me know @amyehodge. I'll try to get this updated within the next couple of days.
