### ISSUE TITLE
default branch after import is not gh-pages

### ISSUE THREAD

**Issue by kcranston** [carpentries/training-template#36]
When you import this repository, the default branch is `fix-18`, not `gh-pages`. This is confusing when you import and merrily change the index file and then wonder why your website never updates. :(

I don't have access to the settings, so I can't fix this.

**Comment by fmichonneau** [comment]
the default branch for this repo is set to `gh-pages`. But I just tried to import the repo and yet a different branch was used as the default in my freshly imported copy of the repo.

Looking at the GitHub docs and some googling doesn't seem to bring any solution for this issue...

**Comment by kcranston** [comment]
Hmm... Interesting. Thanks for investigating. Is that an unmerged feature branch? If not, what happens if you delete it?

**Comment by fmichonneau** [comment]
not enough coffee yet :sleeping:

I had imported the wrong repo... with this one, I also get `fix-18` as the default branch in the imported repo. Based on my previous mistake though, it seems that GitHub chooses the branch that comes first in alphabetical order as the default branch in the newly imported repository instead of the one used repository that is used as the source.

**Comment by kcranston** [comment]
Ha! ☕ 

We should change the import instructions to include:

1. A step to change the default branch
2. A note later for 'is your site not updating after you change the index file?'

**Comment by arokem** [comment]
This one just bit me too

**Comment by jcoliver** [comment]
Is `fix-18` still active? Could we delete that branch?

**Comment by ChristinaLK** [comment]
still having issues with this!

**Comment by Denubis** [comment]
Would you folks like me to merge fix-18 into gh-pages? (also, just bitten by this myself)

**Comment by Denubis** [comment]
At the very least, can you change the default branch to gh-pages? https://help.github.com/en/articles/creating-and-deleting-branches-within-your-repository

**Comment by fmichonneau** [comment]
gh-pages is now the only branch in this repo
