### ISSUE TITLE
index.md instructions should indicate "ttt" as at least an option

### ISSUE THREAD

**Issue by symulation** [carpentries/training-template#38]
and very likely _the_ option

**Comment by symulation** [comment]
scratch the "_the_".  This template is for everything.

**Comment by symulation** [comment]
No.  this is just for training.

**Comment by fmichonneau** [comment]
for this repo which is only used for Instructor Training events, the default is "cp" in the _config.yml, for which "Instructor Training events" is listed as an example in the comments.
