### ISSUE TITLE
Update recordign text for online workshops

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/training-template#56]
Can we have help applying the logic that the workshop tempalte uses for online vs in person and then toggle off the "have somethign to take a recording" turned off for online workshops?

@fmichonneau or @zkamvar Can you help with this?

**Comment by fmichonneau** [comment]
Hi Sarah,

A while back (before pandemic times), I had introduced support to have events be in-person, online, or both: https://github.com/carpentries/training-template/pull/22

This is a little clunky and was merged before its usage was documented. 

Would it make sense to simplify this to use the same approach as regular workshops (at least for now)?

**Comment by brownsarahm** [comment]
I think the same approach as regular workshops would make it eaiser for trainers since most also have used the regular workshop template.
