### ISSUE TITLE
Add Library Carpentry links and references

### ISSUE THREAD

**Issue by raynamharris** [carpentries/training-template#7]
- Library Carpentry is not mentioned on the landing page (aka the README.md file) here:
https://github.com/swcarpentry/training-template
- There is no link to the Library Carpentry website on the about page (http://swcarpentry.github.io/instructor-training/about/) which I think is pulled from this html file (https://github.com/swcarpentry/training-template/blob/gh-pages/_includes/carpentries.html)

This helps fix https://github.com/ErinBecker/instructor-training-reorg/issues/37

**Comment by raynamharris** [comment]
Okay, maybe LC doesn't need to be added to the README.md, but it does make sense to update the html file (that has a short blurb about LC and its logo) to hyperlink to the LC website.

**Comment by ErinBecker** [comment]
Thanks @raynamharris - just noticed today I don't have merge access to this repo. Will merge as soon as I do.

**Comment by ErinBecker** [comment]
@raynamharris This is odd. The about page (http://carpentries.github.io/instructor-training/about/) does have a paragraph about Library Carpentry, but like you said, it doesn't have a link. I went to the about page markdown file to add a link, and then to https://github.com/swcarpentry/training-template/blob/gh-pages/_includes/carpentries.html, but there is no text in that file about Library Carpentry at all. In fact, there is no match for "librarians" in the training-template repo at all. So where is that text coming from?

@rgaiacs - Do you know?

**Comment by weaverbel** [comment]
If you need any LC info, the website is http://librarycarpentry.github.io/ @ErinBecker @raynamharris @rgaiacs The website lists what it is `Software and data skills for library professionals` and links to all the lessons and workshops as well.

**Comment by rgaiacs** [comment]
> This is odd. The about page (http://carpentries.github.io/instructor-training/about/) does have a paragraph about Library Carpentry, but like you said, it doesn't have a link. I went to the about page markdown file to add a link, and then to https://github.com/swcarpentry/training-template/blob/gh-pages/_includes/carpentries.html, but there is no text in that file about Library Carpentry at all. In fact, there is no match for "librarians" in the training-template repo at all. So where is that text coming from?

@ErinBecker You only need to look at the right link: https://github.com/carpentries/instructor-training/blob/gh-pages/_includes/carpentries.html. You look at `swcarpentry/training-template` instead of `carpentries/instructor-training`. Is very easy to type the wrong link or get a bad suggestion from your web browser. Next time, use the edit link at the navigation bar.

**Comment by ErinBecker** [comment]
Thanks @rgaiacs!

I've added a link to LC in the About page now (through _includes/carpentries.html), and will close this issue. I think, however, that we should make this change in the styles template as well and will put in a PR there.

**Comment by ErinBecker** [comment]
It looks like @rgaiacs already took care of adding the link to LC. https://github.com/swcarpentry/styles/blob/gh-pages/_includes/carpentries.html
