### ISSUE TITLE
job build-website error, doesn't seem to actually stop the build

### ISSUE THREAD

**Issue by JCSzamosi** [carpentries/training-template#90]
I built a training workshop website and, although the website does appear to have built fine (ttps://jcszamosi.github.io/2024-02-01-ttt-online-est/) github nonetheless gave me a job error I did not understand: https://github.com/JCSzamosi/2024-02-01-ttt-online-est/actions/runs/7631195377

This error happened on both commits. @sstevens2 suggested I link to [#815](https://github.com/carpentries/workshop-template/issues/815) of the workshop-template repo in case the problems are related.

**Comment by tobyhodges** [comment]
Thanks for reporting this, @JCSzamosi. It was an inconsistency between how I fixed a previous problem and how Zhian had done it for the workshop website template. Turns out Zhian's solution was better than mine.

Fixed with efcf032
